// import { Cairo } from "next/font/google";
import localfont from 'next/font/local'
import "./globals.css";
import Footer from "@/components/Footer";
import Provider from "./Provider";
import Header from "@/components/Header/Header";

// const inter = Cairo({ weight : '200', subsets: ["arabic"] });
const fontLoacl = localfont({
  src: [{
    path: "../../public/font/alfont_com_AlFont_com_DINNextLTArabic-Medium.ttf",
    weight:"700"
  } ,

],
variable: "--font-local",
})
export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body style={fontLoacl.style} className={fontLoacl.variable}>

        <Provider>
        {children}
        <Footer/>
        </Provider>
      </body>
    </html>
  );
}
