import SideBar from "./_components/Sidbar";


export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    // flex flex-row-reverse bg-[#F7F7F7]
    <div className="">
          {/* <SideBar/> */}
          {children}
    </div>
  );
}
