import Password from "@/components/Password";
import SideBar from "./_components/Sidbar";
import SideBar2 from "./_components/Sidbar2";
import Login from "@/components/form/Login";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    // flex flex-row-reverse bg-[#F7F7F7]
    <div className="flex flex-row-reverse bg-[#F7F7F7]">
      <SideBar2 />

      {children}
    </div>
  );
}
